# Paths to user settings for latexindent.pl
#
# Note that the settings will be read in the order you
# specify here- each successive settings file will overwrite
# the variables that you specify
# See https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html.

paths:
- /workdir/.latexindentrc.yaml
- /root/.latexindentrc.yaml
